services:
  ubuntu:
    image: view_count
      container_name: view_count
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - ./entrypoint.sh:/usr/sbin/entrypoint.sh
    - ./cron/:/etc/cron.d/
    - ./files/:/root/files/
    environment:
    - TZ=Asia/Seoul
    command: >
    sh -c "rm -rf /etc/localtime"
    sh -c "ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime"
  restart: on-failure